stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project Projects/Frameworks/CordialSDK/CordialSDK.xcodeproj -scheme CordialSDK | xcpretty
    - xcodebuild test -project Projects/Frameworks/CordialSDK/CordialSDK.xcodeproj -scheme CordialSDK -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' | xcpretty -s
    - xcodebuild clean -project Projects/Frameworks/CordialAppExtensions/CordialAppExtensions.xcodeproj -scheme CordialAppExtensions | xcpretty
    - xcodebuild test -project Projects/Frameworks/CordialAppExtensions/CordialAppExtensions.xcodeproj -scheme CordialAppExtensions -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' | xcpretty -s
  tags:
    - ios
