# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CordialDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'IQKeyboardManagerSwift'
    pod 'CordialSDK', :git => 'git@gitlab.com:CordialExperiences/mobile/ios-sdk.git'

    target 'NotificationServiceExtension' do
      use_frameworks!
      pod 'CordialAppExtensions', :git => 'git@gitlab.com:CordialExperiences/mobile/ios-sdk.git'
    end

  target 'CordialDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CordialDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
