# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CordialDemo_Objective-C' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
    pod 'CordialSDK', :git => 'git@gitlab.com:cordialinc/mobile-sdk/ios-sdk.git'

  target 'NotificationServiceExtension' do
    platform :ios, '11.0'
    use_frameworks!
    pod 'CordialAppExtensions_Objective-C', :git => 'git@gitlab.com:cordialinc/mobile-sdk/ios-sdk.git'
  end

  target 'CordialDemo_Objective-CTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CordialDemo_Objective-CUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
