# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'CordialDemo_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CordialSDK', :git => 'git@gitlab.com:cordialinc/mobile-sdk/ios-sdk.git'

  target 'CordialDemo_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CordialDemo_SwiftUIUITests' do
    # Pods for testing
  end

end
